language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - ruby-head
  - jruby-head
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
script: rspec spec
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  recipients:
    - iamdoomspork@gmail.com
